/*
 * phonet.h
 * --------
 *
 * Phonetic rules for "phonet.c"  ("Hannoveraner Phonetik").
 *
 * Copyright (c):
 * 1999-2008:  Joerg MICHAEL, Adalbert-Stifter-Str. 11, 30655 Hannover, Germany
 *     and
 * (version 1.0) 1999:  Heise Verlag, Helstorfer Str. 7, 30625 Hannover, Germany
 *
 * SCCS: @(#) phonet.h  1.5  2008-11-30
 *
 * This program is subject to the GNU Lesser General Public License (LGPL)
 * (formerly known as GNU Library General Public Licence)
 * as published by the Free Software Foundation; either version 2 of the
 * License, or (at your option) any later version.
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * You should have received a copy of the GNU Library General Public License
 * along with this program; if not, write to the
 * Free Software Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.
 *
 * Actually, the LGPL is __less__ restrictive than the better known GNU General
 * Public License (GPL). See the GNU Library General Public License or the file
 * LIB_GPLP.TXT for more details and for a DISCLAIMER OF ALL WARRANTIES.
 *
 * There is one important restriction: If you modify this program in any way
 * (e.g. add or change phonetic rules or modify the underlying logic or
 * translate this program into another programming language), you must also
 * release the changes under the terms of the LGPL.
 * That means you have to give out the source code to your changes,
 * and a very good way to do so is mailing them to the address given below.
 * I think this is the best way to promote further development and use
 * of this software.
 *
 * If you have any remarks, feel free to e-mail to:
 *     ct@ct.heise.de
 *
 * The author's email address is:
 *    astro.joerg@googlemail.com
 */


#ifndef _PHONET_H_
#define _PHONET_H_

#include <stdio.h>
#include <stdlib.h>

#include "ph_ext.h"


#define  PHONET_VERSION  "version 1.5, 2008-11-30"

/****  we assume 1 byte chars  ****/
#define  HASH_COUNT    256

/****  macro to make the rules easier readable  ****/
#define  null  NULL


/****  end marker for string table  ****/
static char PHONET_END[] = "";

static const char *phonet_language = "unknown";
static int  *phonet_init = NULL;
static int  *phonet_hash = NULL;
static int  (*phonet_hash_1)[26][28] = NULL;   /***  these are pointers  ***/
static int  (*phonet_hash_2)[26][28] = NULL;   /***  to  array[26][28]   ***/
static const char **phonet_rules = NULL;


/****  Syntax for phonetic rules:               ****/
/****    <search_string>  <1st_rule> <2nd_rule> ****/
/****  Syntax for search strings:               ****/
/****    <word> [<->..] [<] [<0-9>] [^[^]] [$]  ****/

/****  Remarks:                                 ****/
/****  a) All phonetic rules must be written    ****/
/****     in upper case.                        ****/
/****  b) The end of <word> may contain as an   ****/
/****     optional simple regular expression    ****/
/****     one array of letters (or umlaut's)    ****/
/****     enclosed in '(' and ')'.              ****/
/****  c) Rules with a '<' demand that the      ****/
/****     replacement string may not be longer  ****/
/****     than the search string.               ****/
/****  d) The placement of rules determines     ****/
/****     their priority. Therefore, the rules  ****/
/****     for "SH" must be placed before the    ****/
/****     rules for "S"                         ****/
/****     (otherwise, a conversion error will   ****/
/****      occur for "SH").                     ****/



#ifdef PHONET_ENGLISH

/*
 *
 * UNDER CONSTRUCTION
 * (no rules available at this time)
 *
 */

#endif    /****  PHONET_ENGLISH  ****/




#ifdef PHONET_NO_LANGUAGE

static const char *phonet_language_no_language = "no language";
static int  phonet_init_no_language = 0;
static int  phonet_hash_no_language [HASH_COUNT];
static int  phonet_hash_no_language_1 [26][28];
static int  phonet_hash_no_language_2 [26][28];

/****  Phonetic rules for "no language"   ****/
/****  (i.e. umlauts will be "expanded")  ****/

static const char *phonet_rules_no_language[] =
  {
/****  separator chars  ****/
    "\264",               " ",       " ",
    "\222",               " ",       " ",
    "'",               " ",       " ",
    "`",               "",        "",
    "`$",              "",        "",
    "\"",              " ",       " ",
    ",",               ",",       ",",
    ";",               ",",       ",",
    "-",               " ",       " ",
    " ",               " ",       " ",
    ".",               ".",       ".",
    ":",               ".",       ".",
/****  German umlauts  ****/
    "\304",               "AE",      "AE",
    "\326",               "OE",      "OE",
    "\334",               "UE",      "UE",
    "\337",               "S",       "S",
/****  international umlauts  ****/
    "\300",               "A",       "A",
    "\301",               "A",       "A",
    "\302",               "A",       "A",
    "\303",               "A",       "A",
    "\305",               "A",       "A",
    "\306",               "AE",      "AE",
    "\307",               "C",       "C",
    "\320",               "DJ",      "DJ",
    "\310",               "E",       "E",
    "\311",               "E",       "E",
    "\312",               "E",       "E",
    "\313",               "E",       "E",
    "\314",               "I",       "I",
    "\315",               "I",       "I",
    "\316",               "I",       "I",
    "\317",               "I",       "I",
    "\321",               "NH",      "NH",
    "\322",               "O",       "O",
    "\323",               "O",       "O",
    "\324",               "O",       "O",
    "\325",               "O",       "O",
    "\214",               "OE",      "OE",
    "\330",               "OE",      "OE",
    "\212",               "SH",      "SH",
    "\336",               "TH",      "TH",
    "\331",               "U",       "U",
    "\332",               "U",       "U",
    "\333",               "U",       "U",
    "\335",               "Y",       "Y",
    "\237",               "Y",       "Y",
    "\216",               "Z",       "Z",
/****  "normal" letters (A-Z)  ****/
    "ALEH^$",          "OLEK",    "ULEK",
    "ANDRI(IJY)^$",    "ANDREI",  "ANTREI",
    "BORYS^$",         "BORIS",   null,
    "GALYNA^$",        "GALINA",  null,
    "HAMA(DT)^$",      "HAMET",   "ANET",
    "HAMMA(DT)^$",     "HAMET",   "ANET",
    "IHAR^$",          "IGOR",    "IKUR",
    "IHOR^$",          "IGOR",    "IKUR",
    "IRYNA^$",         "IRINA",   null,
    "KATERYNA^$",     "KATERINA", null,
    "KATSIARYNA^$",   "KATERINA", null,
    "KOSTYANTYN^$",  "KONSTANTIN", "KUNZTANTIN",
    "LARYSA^$",        "LARISA",  null,
    "LUDMYLA^$",       "LUTMILA", null,
    "LYUDMYLA^$",     "LIUTMILA", null,
    "MARYNA^$",        "MARINA",  null,
    "MOHAM---^^",      "MO",      "NU",
    "MOUHAM---^^",     "MO",      "NU",
    "MUHAM---^^",      "MO",      "NU",
    "MYKHA(IJY)----<^",  "MI",    "NI",
    "MYKOLA^$",        "NIKOLEI", "NIKULEI",
    "MC^",             "MAC",     "MAC",
    "MC^",             "MAC",     "MAC",
    "M\264^",             "MAC",     "MAC",
    "M'^",             "MAC",     "MAC",
    "O\264^",             "O",       "O",
    "O'^",             "O",       "O",
    "SASA^$",          "SASHA",   null,
    "SERGI(IJY)^$",    "SERGEI",  "ZERKEI",
    "SERHI(IJY)^$",    "SERGEI",  "ZERKEI",
    "TATSIANA^$",      "TATIANA", "TATIANA",
    "ULADZIMIR^$",    "WLADIMIR", "FLATINIR",
    "VAN DEN ^",      "VANDEN",   "VANDEN",
    "VASYL^$",         "WASIL",   null,
    "VIKTAR^$",        "WIKTOR",  "FIKTUR",
    "VOLHA^$",         "OLGA",    "ULKA",
    "VOLODIMIR^$",    "WLADIMIR", null,
    "VOLODYMYR^$",    "WLADIMIR", null,

    PHONET_END,      PHONET_END,  PHONET_END
  };

#endif    /****  PHONET_NO_LANGUAGE  ****/




#ifdef PHONET_GERMAN

static const char *phonet_language_german = "German";
static int  phonet_init_german = 0;
static int  phonet_hash_german [HASH_COUNT];
static int  phonet_hash_german_1 [26][28];
static int  phonet_hash_german_2 [26][28];

/****  Phonetic rules for German.     ****/
/****  First Rules:                   ****/
/****    The letters \304,\337,C,J,Q,V,Y    ****/
/****    will "disappear".            ****/
/****  Second Rules (less accurate):  ****/
/****    The letters \304,\334,\337,C,D,       ****/
/****    G,H,J,O,P,Q,S,V,W,X,Y        ****/
/****    will "disappear".            ****/

static const char *phonet_rules_german[] =
  {
/****  separator chars  ****/
    "\264",               " ",       " ",
    "\222",               " ",       " ",
    "'",               " ",       " ",
    "`",               "",        "",
    "`$",              "",        "",
    "\"",              " ",       " ",
    ",",               " ",       " ",
    ";",               " ",       " ",
    "-",               "",       "",
    " ",               "",       "",
    ".",               "",       "",
    ":",               ".",       ".",
/****  German umlauts  ****/
    "\304",               "AE",       "AE",
    "\304E",              "AE",       "AE",
    "\304U<",             "AEU",      "AEU",
    "\304V(AEOU)-<",      "AEW",      null,
    "\304$",              "AE",       null,
    "\304<",              "AE",      "E",
    "\326E",              "OE",       "\326",
    "\326U",              "OE",       "\326",
    "\326VER--<",         "OEW",      null,
    "\326V(AOU)-",        "OEW",      null,
    "\326",               "OE",      "OE",
    "\334BEL(GNRW)-^^",   "UEBL ",    "IBL ",
    "\334BER^^",          "UEBER",     "IBA",
    "\334E",              "UE",       "I",
    "\334VER--<",         "UEW",      null,
    "\334V(AOU)-",        "UE",      null,
    "\334",               "UE",      "I",
    "\337CH<",            null,      "Z",
    "\337<",              "S",       "Z",
/****  international umlauts  ****/
    "\300",              "A",       "A",
    "\301",              "A",       "A",
    "\302",              "A",       "A",
    "\303",              "A",       "A",
    "\305",              "A",       "A",
    "\306ER-",            "E",       "E",
    "\306U",             "EU",      "EU",
    "\306V(AEOU)-",      "EW",      null,
    "\306$",              "AE",       null,
    "\306",              null,      "E",
    "\306",               "E",       null,
    "\307",               "Z",       "Z",
    "\320\320-",             "",        "",
    "\320",               "DI",      "TI",
    "\310",              "E",       "E",
    "\311",              "E",       "E",
    "\312",              "E",       "E",
    "\313",               "E",       "E",
    "\314",              "I",       "I",
    "\315",              "I",       "I",
    "\316",              "I",       "I",
    "\317",               "I",       "I",
    "\321\321-",             "",        "",
    "\321",               "NI",      "NI",
    "\322",              "O",       "U",
    "\323",              "O",       "U",
    "\324",              "O",       "U",
    "\325",              "O",       "U",
    "\214",              "OE",       "\326",
    "\330(IJY)-",        "E",       "E",
    "\330",              "OE",       "\326",
    "\212",               "SH",      "Z",
    "\336",               "T",       "T",
    "\331",              "U",       "U",
    "\332",              "U",       "U",
    "\333",              "U",       "U",
    "\335",              "I",       "I",
    "\237",              "I",       "I",
    "\216",              "Z",       "Z",
/****  "normal" letters (A-Z)  ****/
    "ABELLE$",         "ABL",     "ABL",
    "ABELL$",          "ABL",     "ABL",
    "ABIENNE$",        "ABIN",    "ABIN",
    "AHME(DT)^$",      "ACHMET",  "AKNET",
    "ACEY$",           "AZI",     "AZI",
    "ADV",             "ATW",     null,
    "AEGL-",           "EK",      null,
    "AEU<",            "EU",      "EU",
    "AE2",             "E",       "E",
    "AFTRAUBEN------", "AFT ",    "AFT ",
    "AGL-1",           "AK",      null,
    "AGNI-^",          "AKN",     "AKN",
    "AGNIE-",          "ANI",     "ANI",
    "AGN(AEOU)-$",     "ANI",     "ANI",
    "AH(AIO\326U\334Y)-",    "AH",      null,
    "AIA2",            "AIA",     "AIA",
    "AIE$",            "E",       "E",
    "AILL(EOU)-",      "ALI",     "ALI",
    "AINE$",           "EN",      "EN",
    "AIRE$",           "ER",      "ER",
    "AIR-",            "E",       "E",
    "AISE$",           "ES",      "EZ",
    "AISSANCE$",       "ESANS",   "EZANZ",
    "AISSE$",          "ES",      "EZ",
    "AIX$",            "EX",      "EX",
    "AJ(A\304E\310\311\312IO\326U\334)--", "A",     "A",
    "AKTIE",           "AXIE",    "AXIE",
    "AKTUEL",          "AKTUEL",  null,
    "ALEH^$",          "OLEK",    "ULEK",
    "ALIA(KS)-^",      "ALE",     "ALE",
    "ALOI^",           "ALOI",    "ALUI",  /** Do NOT merge these rules  **/
    "ALOY^",           "ALOI",    "ALUI",  /** (needed by "check_rules") **/
    "AMATEU(RS)-",     "AMATOE",   "ANAT\326",
    "ANCH(OEI)-",      "ANSH",    "ANZ",
    "ANDERGEGANG----", "ANDA GE", "ANTA KE",
    "ANDERGEHE----",   "ANDA ",   "ANTA ",
    "ANDERGESETZ----", "ANDA GE", "ANTA KE",
    "ANDERGING----",   "ANDA ",   "ANTA ",
    "ANDERSETZ(ET)-----", "ANDA ", "ANTA ",
    "ANDERZUGEHE----", "ANDA ZU ", "ANTA ZU ",
    "ANDERZUSETZE-----", "ANDA ZU ", "ANTA ZU ",
    "ANDRI(IJY)^$",    "ANDREI",  "ANTREI",
    "ANDR$",           "ANDA",    "ANTA",
    "ANER(BKO)---^^",  "AN",      null,
    "ANHAND---^$",     "AN H",    "AN ",
    "ANH(A\304EIO\326U\334Y)--^^", "AN",   null,
    "ANIELLE$",        "ANIEL",   "ANIL",
    "ANIEL",           "ANIEL",   null,
    "ANSTELLE----^$",  "AN ST",   "AN ZT",
    "ANTI^^",          "ANTI",    "ANTI",
    "ANVER^^",         "ANFA",    "ANFA",
    "ATIA$",           "ATIA",    "ATIA",
    "ATIA(NS)--",      "ATI",     "ATI",
    "ATI(A\304O\326U\334)-",    "AZI",     "AZI",
    "AUAU--",          "",        "",
    "AUERE$",          "AUERE",   null,
    "AUERE(NS)-$",     "AUERE",   null,
    "AUERE(AIOUY)--",  "AUER",    null,
    "AUER(A\304IO\326U\334Y)-", "AUER",    null,
    "AUER<",           "AUA",     "AUA",
    "AUF^^",           "AUF",     "AUF",
    "AULT$",           "O",       "U",
    "AUR(BCDFGKLMNQSTVWZ)-", "AUA", "AUA",
    "AUR$",            "AUA",     "AUA",
    "AUSSE$",          "OS",      "UZ",
    "AUS(ST)-^",       "AUS",     "AUS",
    "AUS^^",           "AUS",     "AUS",
    "AUTOFAHR----",    "AUTO ",   "AUTU ",
    "AUTO^^",          "AUTO",    "AUTU",
    "AUX(IY)-",        "AUX",     "AUX",
    "AUX",             "O",       "U",
    "AU",              "AU",      "AU",
    "AVER--<",         "AW",      null,
    "AVIER$",          "AWIE",    "AFIE",
    "AV(E\310\311\312I)-^",     "AW",      null,
    "AV(AOU)-",        "AW",      null,
    "AYRE$",           "EIRE",    "EIRE",
    "AYRE(NS)-$",      "EIRE",    "EIRE",
    "AYRE(AIOUY)--",   "EIR",     "EIR",
    "AYR(A\304IO\326U\334Y)-",  "EIR",     "EIR",
    "AYR<",            "EIA",     "EIA",
    "AYER--<",         "EI",      "EI",
    "AYSE^$",          "EISHE",   null,
    "AY(A\304EIO\326U\334Y)--", "A",       "A",
    "A\313",              "E",       "E",
    "A(IJY)<",         "EI",      "EI",
    
    "BF.",             "BANHAU",  "BANHAU",
    
    "BABY^$",          "BEBI",    "BEBI",
    "BAB(IY)^",        "BEBI",    "BEBI",
    "BEAU^$",          "BO",      null,
    "BEA(BCMNRU)-^",   "BEA",     "BEA",
    "BEAT(AEIMORU)-^", "BEAT",    "BEAT",
    "BEE$",            "BI",      "BI",
    "BEIGE^$",         "BESH",    "BEZ",
    "BENOIT--",        "BENO",    "BENU",
    "BER(DT)-",        "BER",     null,
    "BERN(DT)-",       "BERN",    null,
    "BE(LMNRST)-^",    "BE",      "BE",
    "BETTE$",          "BET",     "BET",
    "BEVOR^$",         "BEFOR",   null,
    "BIC$",            "BIZ",     "BIZ",
    "BORYS^$",         "BORIS",   null,
    "BOWL(EI)-",       "BOL",     "BUL",
    "BP(A\304E\310\311\312I\314\315\316O\326RU\334Y)-", "B", "B",
    "BRINGEND-----^",  "BRI",     "BRI",
    "BRINGEND-----",   " BRI",    " BRI",
    "BROW(NS)-",       "BRAU",    "BRAU",
    "BUDGET7",         "BUEGE",    "BIKE",
    "BUFFET7",         "BUEFE",    "BIFE",
    "BYLLE$",          "BILE",    "BILE",
    "BYLL$",           "BIL",     "BIL",
    "BYPA--^",         "BEI",     "BEI",
    "BYTE<",           "BEIT",    "BEIT",
    "BY9^",            "BUE",      null,
    "B(S\337Z)$",         "BS",      null,
    "CACH(EI)-^",      "KESH",    "KEZ",
    "CAE--",           "Z",       "Z",
    "CA(IY)$",         "ZEI",     "ZEI",
    "CE(EIJUY)--",     "Z",       "Z",
    "CENT<",           "ZENT",    "ZENT",
    "CERST(EI)----^",  "KE",      "KE",
    "CER$",            "ZA",      "ZA",
    "CE3",             "ZE",      "ZE",
    "CH'S$",           "X",       "X",
    "CH\264S$",           "X",       "X",
    "CHAO(ST)-",       "KAO",     "KAU",
    "CHAMPIO-^",       "SHEMPI",  "ZENBI",
    "CHAR(AI)-^",      "KAR",     "KAR",
    "CHAU(CDFSVWXZ)-", "SHO",     "ZU",
    "CH\304(CF)-",        "SHAE",     "ZE",
    "CHE(CF)-",        "SHE",     "ZE",
    "CHEM-^",          "KE",      "KE",    /**  or: "CHE", "KE" **/
    "CHEQUE<",         "SHEK",    "ZEK",
    "CHI(CFGPVW)-",    "SHI",     "ZI",
    "CH(AEUY)-<^",     "SH",      "Z",
    "CHK-",            "",        "",
    "CHO(CKPS)-^",     "SHO",     "ZU",
    "CHRIS-",          "KRI",     null,
    "CHRO-",           "KR",      null,
    "CH(LOR)-<^",      "K",       "K",
    "CHST-",           "X",       "X",
    "CH(S\337XZ)3",       "X",       "X",
    "CHTNI-3",         "CHN",     "KN",
    "CH^",             "K",       "K",     /**  or: "CH", "K"  **/
    "CH",              "CH",      "K",
    "CIC$",            "ZIZ",     "ZIZ",
    "CIENCEFICT----",  "EIENS ",  "EIENZ ",
    "CIENCE$",         "EIENS",   "EIENZ",
    "CIER$",           "ZIE",     "ZIE",
    "CYB-^",           "ZEI",     "ZEI",
    "CY9^",            "ZUE",      "ZI",
    "C(IJY)-<3",       "Z",       "Z",
    "CLOWN-",          "KLAU",    "KLAU",
    "CCH",             "Z",       "Z",
    "CCE-",            "X",       "X",
    "C(CK)-",          "",        "",
    "CLAUDET---",      "KLO",     "KLU",
    "CLAUDINE^$",      "KLODIN",  "KLUTIN",
    "COACH",           "KOSH",    "KUZ",
    "COLE$",           "KOL",     "KUL",
    "COUCH",           "KAUSH",   "KAUZ",
    "COW",             "KAU",     "KAU",
    "CQUES$",          "K",       "K",
    "CQUE",            "K",       "K",
    "CRASH--9",        "KRE",     "KRE",
    "CREAT-^",         "KREA",    "KREA",
    "CST",             "XT",      "XT",
    "CS<^",            "Z",       "Z",
    "C(S\337X)",          "X",       "X",
    "CT'S$",           "X",       "X",
    "CT(S\337XZ)",        "X",       "X",
    "CZ<",             "Z",       "Z",
    "C(\310\311\312\314\315\316\335)3",     "Z",       "Z",
    "C.^",             "C.",      "C.",
    "C\304-",             "Z",       "Z",
    "C\334$",             "ZUE",      "ZI",
    "C'S$",            "X",       "X",
    "C<",              "K",       "K",
    "DAHER^$",         "DAHER",   null,
    "DARAUFFOLGE-----", "DARAUF ", "TARAUF ",
    "DAVO(NR)-^$",     "DAFO",    "TAFU",
    "DD(SZ)--<",       "",        "",
    "DD9",             "D",       null,
    "DEPOT7",          "DEPO",    "TEBU",
    "DESIGN",          "DISEIN",  "TIZEIN",
    "DE(LMNRST)-3^",   "DE",      "TE",
    "DETTE$",          "DET",     "TET",
    "DH$",             "T",       null,
    "DIC$",            "DIZ",     "TIZ",
    "DIDR-^",          "DIT",     null,
    "DIEDR-^",         "DIT",     null,
    "DJ(AEIOU)-^",     "I",       "I",
    "DMITR-^",         "DIMIT",   "TINIT",
    "DMYTR(IO)",       "DIMITRI", "TINITRI",
    "DRY9^",           "DRUE",     null,
    "DT-",             "",        "",
    "DUIS-^",          "DUE",      "TI",
    "DURCH^^",         "DURCH",   "TURK",
    "DVA$",            "TWA",     null,
    "DY9^",            "DUE",      null,
    "DYS$",            "DIS",     null,
    "DS(CH)--<",       "T",       "T",
    "DST",             "ZT",      "ZT",
    "DZMITR--",        "DIMI",    "TINI",
    "DZS(CH)--",       "T",       "T",
    "D(S\337Z)",          "Z",       "Z",
    "D(A\304EIO\326RU\334Y)-",  "D",       null,
    "D(\300\301\302\303\305\310\311\312\314\315\316\331\332\333)-", "D",    null,
    "D'H^",            "D",       "T",
    "D\264H^",            "D",       "T",
    "D`H^",            "D",       "T",
    "D'S3$",           "Z",       "Z",
    "D\264S3$",           "Z",       "Z",
    "D^",              "D",       null,
    "D",               "T",       "T",
    "EAULT$",          "O",       "U",
    "EAUX$",           "O",       "U",
    "EAU",             "O",       "U",
    "EAV",             "IW",      "IF",
    "EAS3$",           "EAS",     null,
    "EA(A\304EIO\326\334Y)-3",  "EA",      "EA",
    "EA3$",            "EA",      "EA",
    "EA3",             "I",       "I",
    "EBENSO^$",        "EBNSO",   "EBNZU",
    "EBENSO^^",        "EBNSO ",  "EBNZU ",
    "EBEN^^",          "EBN",     "EBN",
    "EE9",             "E",       "E",
    "EGL-1",           "EK",      null,
    "EHE(IUY)--1",     "EH",      null,
    "EHUNG---1",       "E",       null,
    "EH(A\304IO\326U\334Y)-1",  "EH",      null,
    "EIEI--",          "",        "",
    "EIERE^$",         "EIERE",   null,
    "EIERE$",          "EIERE",   null,
    "EIERE(NS)-$",     "EIERE",   null,
    "EIERE(AIOUY)--",  "EIER",    null,
    "EIER(A\304IO\326U\334Y)-", "EIER",    null,
    "EIER<",           "EIA",     null,
    "EIGL-1",          "EIK",     null,
    "EIGH$",           "EI",      "EI",
    "EIH--",           "E",       "E",
    "EILLE$",          "EI",      "EI",
    "EIR(BCDFGKLMNQSTVWZ)-", "EIA", "EIA",
    "EIR$",            "EIA",     "EIA",
    "EITRAUBEN------", "EIT ",    "EIT ",
    "EI",              "EI",      "EI",
    "EJ$",             "EI",      "EI",
    "ELIZ^",           "ELIS",    null,
    "ELZ^",            "ELS",     null,
    "EL-^",            "E",       "E",
    "ELANG----1",      "E",       "E",
    "EL(DKL)--1",      "E",       "E",
    "EL(MNT)--1$",     "E",       "E",
    "ELYNE$",          "ELINE",   "ELINE",
    "ELYN$",           "ELIN",    "ELIN",
    "EL(A\304E\310\311\312I\314\315\316O\326U\334Y)-1", "EL", "EL",
    "EL-1",            "L",       "L",
    "EM-^",            null,      "E",
    "EM(DFKMPQT)--1",  null,      "E",
    "EM(A\304E\310\311\312I\314\315\316O\326U\334Y)--1", null, "E",
    "EM-1",            null,      "N",
    "ENGAG-^",         "ANGA",    "ANKA",
    "EN-^",            "E",       "E",
    "ENTUEL",          "ENTUEL",  null,
    "EN(CDGKQSTZ)--1", "E",       "E",
    "EN(A\304E\310\311\312I\314\315\316NO\326U\334Y)-1", "EN", "EN",
    "EN-1",            "",        "",
    "ERH(A\304EIO\326U\334)-^", "ERH",     "ER",
    "ER-^",            "E",       "E",
    "ERREGEND-----",   " ER",     " ER",
    "ERT1$",           "ERT",      null,
    "ER(DGLKMNRQTZ\337)-", "ER",    null,
    "ER(A\304E\310\311\312I\314\315\316O\326U\334Y)-", "ER", "A",
    "ER1$",            "ER",       "A",
    "ER<1",            "ER",       "A",
    "ETAT7",           "ETA",     "ETA",
    "ETI(A\304O\326\334U)-",    "EZI",     "EZI",
    "EUERE$",          "EUERE",   null,
    "EUERE(NS)-$",     "EUERE",   null,
    "EUERE(AIOUY)--",  "EUER",    null,
    "EUER(A\304IO\326U\334Y)-", "EUER",    null,
    "EUER<",           "EUA",     null,
    "EUEU--",          "",        "",
    "EUILLE$",         "OE",       "\326",
    "EUR$",            "OER",      "\326R",
    "EUX",             "OE",       "\326",
    "EUSZ$",           "EUS",     null,
    "EUTZ$",           "EUS",     null,
    "EUYS$",           "EUS",     "EUZ",
    "EUZ$",            "EUS",     null,
    "EU",              "EU",      "EU",
    "EVER--<1",        "EW",      null,
    "EV(\304O\326U\334)-1",     "EW",      null,
    "EYER<",           "EIA",     "EIA",
    "EY<",             "EI",      "EI",
    "FACETTE",         "FASET",   "FAZET",
    "FANS--^$",        "FE",      "FE",
    "FAN-^$",          "FE",      "FE",
    "FAULT-",          "FOL",     "FUL",
    "FEE(DL)-",        "FI",      "FI",
    "FEHLER",          "FELA",    "FELA",
    "FE(LMNRST)-3^",   "FE",      "FE",
    "FOERDERN---^",    "FOERD",    "F\326RT",
    "FOERDERN---",     " FOERD",   " F\326RT",
    "FOND7",           "FON",     "FUN",
    "FRAIN$",          "FRA",     "FRA",
    "FRISEU(RS)-",     "FRISOE",   "FRIZ\326",
    "FY9^",            "FUE",      null,
    "F\326RDERN---^",     "FOERD",    "F\326RT",
    "F\326RDERN---",      " FOERD",   " F\326RT",
    "GAGS^$",          "GEX",     "KEX",
    "GAG^$",           "GEK",     "KEK",
    "GALYNA^$",        "GALINA",  null,
    "GD",              "KT",      "KT",
    "GEGEN^^",         "GEGN",    "KEKN",
    "GEGENGEKOM-----", "GEGN ",   "KEKN ",
    "GEGENGESET-----", "GEGN ",   "KEKN ",
    "GEGENKOMME-----", "GEGN ",   "KEKN ",
    "GEGENZUKOM---",  "GEGN ZU ", "KEKN ZU ",
    "GENDETWAS-----$", "GENT ",   "KENT ",
    "GENRE",           "IORE",    "IURE",
    "GE(LMNRST)-3^",   "GE",      "KE",
    "GER(DKT)-",       "GER",     null,
    "GETTE$",          "GET",     "KET",
    "GGF.",            "GF.",     null,
    "GG-",             "",        "",
    "GH",              "G",       null,
    "GI(AOU)-^",       "I",       "I",
    "GION-3",          "KIO",     "KIU",
    "G(CK)-",          "",        "",
    "GJ(AEIOU)-^",     "I",       "I",
    "GMBH^$",          "GMBH",    "GMBH",
    "GNAC$",           "NIAK",    "NIAK",
    "GNON$",           "NION",    "NIUN",
    "GN$",             "N",       "N",
    "GONCAL-^",        "GONZA",   "KUNZA",
    "GRY9^",           "GRUE",     null,
    "G(S\337XZ)-<",       "K",       "K",
    "GUCK-",           "KU",      "KU",
    "GUISEP-^",        "IUSE",    "IUZE",
    "GUI-^",           "G",       "K",
    "GUTAUSSEH------^", "GUT ",   "KUT ",
    "GUTGEHEND------^", "GUT ",   "KUT ",
    "GY9^",            "GUE",      null,
    "G(A\304EILO\326RU\334Y)-", "G",       null,
    "G(\300\301\302\303\305\310\311\312\314\315\316\331\332\333)-", "G",    null,
    "G'S$",            "X",       "X",
    "G\264S$",            "X",       "X",
    "G^",              "G",       null,
    "G",               "G",       "K",
    "HA(HIUY)--1",     "H",       null,
    "HAMA(DT)^$",      "HAMET",   "ANET",
    "HAMMA(DT)^$",     "HAMET",   "ANET",
    "HANDVOL---^",     "HANT ",   "ANT ",
    "HANNOVE-^",       "HANOF",   null,
    "HAVEN7$",         "HAFN",    null,
    "HEAD-",           "HE",      "E",
    "HELIEGEN------",  "E ",      "E ",
    "HESTEHEN------",  "E ",      "E ",
    "HE(LMNRST)-3^",   "HE",      "E",
    "HE(LMN)-1",       "E",       "E",
    "HEUR1$",          "OER",      "\326R",
    "HE(HIUY)--1",     "H",       null,
    "HIH(A\304EIO\326U\334Y)-1", "IH",     null,
    "HLH(A\304EIO\326U\334Y)-1", "LH",     null,
    "HMH(A\304EIO\326U\334Y)-1", "MH",     null,
    "HNH(A\304EIO\326U\334Y)-1", "NH",     null,
    "HOBBY9^",          "HOBI",   null,
    "HOCHBEGAB-----^",  "HOCH ",  "UK ",
    "HOCHTALEN-----^",  "HOCH ",  "UK ",
    "HOCHZUFRI-----^",  "HOCH ",  "UK ",
    "HO(HIY)--1",       "H",      null,
    "HRH(A\304EIO\326U\334Y)-1", "RH",     null,
    "HUH(A\304EIO\326U\334Y)-1", "UH",     null,
    "HUIS^^",          "HUES",     "IZ",
    "HUIS$",           "UES",      "IZ",
    "HUI--1",          "H",       null,
    "HYGIEN^",         "HUEKIEN",  null,
    "HY9^",            "HUE",      null,
    "HY(BDGMNPST)-",   "UE",       null,
    "H.^",             null,      "H.",
    "H\304U--1",          "H",       null,
    "H^",              "H",       "",
    "H",               "",        "",
    "ICHI$",           "ISHI",    "IZI",
    "IEC$",            "IZ",      "IZ",
    "IEDENSTELLE------", "IDN ",  "ITN ",
    "IEI-3",           "",        "",
    "IELL3",           "IEL",     "IEL",
    "IENNE$",          "IN",      "IN",
    "IERRE$",          "IER",     "IER",
    "IERZULAN---",     "IR ZU ",  "IR ZU ",
    "IETTE$",          "IT",      "IT",
    "IEU",             "IOE",      "I\326",
    "IE<4",            "I",       "I",
    "IGL-1",           "IK",      null,
    "IGHT3$",          "EIT",     "EIT",
    "IGNI(EO)-",       "INI",     "INI",
    "IGN(AEOU)-$",     "INI",     "INI",
    "IHAR^$",          "IGOR",    "IKUR",
    "IHER(DGLKRT)--1", "IHE",     null,
    "IHE(IUY)--",      "IH",      null,
    "IHOR^$",          "IGOR",    "IKUR",
    "IH(AIO\326U\334Y)-",    "IH",      null,
    "IJ(AOU)-",        "I",       "I",
    "IJ$",             "I",       "I",
    "IJ<",             "EI",      "EI",
    "IKOLE$",          "IKOL",    "IKUL",
    "ILLAN(STZ)--4",   "ILIA",    "ILIA",
    "ILLAR(DT)--4",    "ILIA",    "ILIA",
    "IMSTAN----^",     "IM ",     "IN ",
    "INDELERREGE------", "INDL ", "INTL ",
    "INFRAGE-----^$",  "IN ",     "IN ",
    "INTERN(AOU)-^",   "INTAN",   "INTAN",
    "INVER-",          "INWE",    "INFE",
    "IRYNA^$",         "IRINA",   null,
    "ITI(A\304IO\326U\334)-",   "IZI",     "IZI",
    "IUSZ$",           "IUS",     null,
    "IUTZ$",           "IUS",     null,
    "IUZ$",            "IUS",     null,
    "IVER--<",         "IW",      null,
    "IVIER$",          "IWIE",    "IFIE",
    "IV(\304O\326U\334)-",      "IW",      null,
    "IV<3",            "IW",      null,
    "IY2",             "I",       null,
    "I(\310\311\312)<4",        "I",       "I",
    "JAUHEN-",         "IEFGE",   "IEFKE",
    "JAVIE---<^",      "ZA",      "ZA",
    "JEANS^$",         "JINS",    "INZ",
    "JEANNE^$",        "IAN",     "IAN",
    "JEAN-^",          "IA",      "IA",
    "JER-^",           "IE",      "IE",
    "JEVHEN-",         "IEFGE",   "IEFKE",
    "JE(LMNST)-",      "IE",      "IE",
    "JI^",             "JI",      null,
    "JOR(GK)^$",       "IOERK",    "I\326RK",
    "J",               "I",       "I",
    "KATERYNA^$",     "KATERINA", null,
    "KATSIARYNA^$",   "KATERINA", null,
    "KC(\304EIJ)-",       "X",       "X",
    "KD",              "KT",      null,
    "KE(LMNRST)-3^",   "KE",      "KE",
    "KG(A\304EILO\326RU\334Y)-", "K",      null,
    "KH<^",            "K",       "K",
    "KIC$",            "KIZ",     "KIZ",
    "KLE(LMNRST)-3^",  "KLE",     "KLE",
    "KOSTYANT(IY)^", "KONSTANTI", "KUNZTANTI",
    "KOTELE-^",        "KOTL",    "KUTL",
    "KREAT-^",         "KREA",    "KREA",
    "KR\334S(TZ)--^",     "KRI",     null,
    "KRYS(TZ)--^",     "KRI",     null,
    "KRY9^",           "KRUE",     null,
    "KSCH---",         "K",       "K",
    "KSH--",           "K",       "K",
    "K(S\337XZ)7",        "X",       "X",    /**** implies "KST" -> "XT" ****/
    "KT'S$",           "X",       "X",
    "KTI(AIOU)-3",     "XI",      "XI",
    "KT(S\337XZ)",        "X",       "X",
    "KY9^",            "KUE",      null,
    "K'S$",            "X",       "X",
    "K\264S$",            "X",       "X",
    "LANGES$",         " LANGES", " LANKEZ",
    "LANGE$",          " LANGE",  " LANKE",
    "LANG$",           " LANK",   " LANK",
    "LARYSA^$",        "LARISA",  null,
    "LARVE-",          "LARF",    "LARF",
    "LD(S\337Z)$",        "LS",      "LZ",
    "LD'S$",           "LS",      "LZ",
    "LD\264S$",           "LS",      "LZ",
    "LEAND-^",         "LEAN",    "LEAN",
    "LEERSTEHE-----^", "LER ",    "LER ",
    "LEICHBLEIB-----", "LEICH ",  "LEIK ",
    "LEICHLAUTE-----", "LEICH ",  "LEIK ",
    "LEIDERREGE------", "LEIT ",  "LEIT ",
    "LEIDGEPR----^",   "LEIT ",   "LEIT ",
    "LEINSTEHE-----",  "LEIN ",   "LEIN ",
    "LEL-",            "LE",      "LE",
    "LE(MNRST)-3^",    "LE",      "LE",
    "LETTE$",          "LET",     "LET",
    "LFGNAG-",         "LFGAN",   "LFKAN",
    "LICHERWEIS----",  "LICHA ", "LIKA ",
    "LIC$",            "LIZ",     "LIZ",
    "LIVE^$",          "LEIF",    "LEIF",
    "LT(S\337Z)$",        "LS",      "LZ",
    "LT'S$",           "LS",      "LZ",
    "LT\264S$",           "LS",      "LZ",
    "LUDMYLA^$",       "LUTMILA", null,
    "LUI(GS)--",       "LU",      "LU",
    "LV(AIO)-",        "LW",      null,
    "LYUDMYLA^$",     "LIUTMILA", null,
    "LY9^",            "LUE",      null,
    "LSTS$",           "LS",      "LZ",
    "LZ(BDFGKLMNPQRSTVWX)-", "LS", null,
    "L(S\337Z)$",         "LS",      null,
    "MAIR-<",          "MEI",     "NEI",
    "MANAG-",          "MENE",    "NENE",
    "MANUEL",          "MANUEL",  null,
    "MARYNA^$",        "MARINA",  null,
    "MASSEU(RS)-",     "MASOE",    "NAZ\326",
    "MATCH",           "MESH",    "NEZ",
    "MAURICE",         "MORIS",   "NURIZ",
    "MBH^$",           "MBH",     "MBH",
    "MB(\337Z)$",         "MS",      null,
    "MB(S\337TZ)-",       "M",       "N",
    "MCG9^",           "MAK",     "NAK",
    "MC9^",            "MAK",     "NAK",
    "MEMOIR-^",        "MEMOA",   "NENUA",
    "MERHAVEN$",       "MAHAFN",  null,
    "ME(LMNRST)-3^",   "ME",      "NE",
    "MEN(STZ)--3",     "ME",      null,
    "MEN$",            "MEN",     null,
    "MICHELLE^$",      "MISHEL",  "NIZEL",
    "MICHEL^$",        "MISHEL",  "NIZEL",
    "MIGUEL-",         "MIGE",    "NIKE",
    "MIKALA-^",        "NIKOL",   null,
    "MIKE^$",          "MEIK",    "NEIK",
    "MITHILFE----^$",  "MIT H",   "NIT ",
    "MN$",             "M",       null,
    "MN",              "N",       "N",
    "MOHAM---^^",      "MO",      "NU",
    "MORDE(CH)9^",     "MORDECH", "NURTEK",
    "MOUHAM---^^",     "MO",      "NU",
    
    "MONTAGNE",        "MUNT",    "MUNT",
    "MONT",            "MUNT",    "MUNT",
    "MT ^",            "MUNT",    "MUNT",
    "MT.^",            "MUNT",    "MUNT",
    
    "MPJUTE-",         "MPUT",    "NBUT",
    "MP(\337Z)$",         "MS",      null,
    "MP(S\337TZ)-",       "M",       "N",
    "MP(BDJLMNPQVW)-", "MB",      "NB",
    "MUHAM---^^",      "MO",      "NU",
    "MYKHA(IJY)----<^",  "MI",    "NI",
    "MYKOLA^$",        "NIKOLEI", "NIKULEI",
    "MY9^",            "MUE",      null,
    "M(\337Z)$",          "MS",      null,
    "M\264G7^",           "MAK",     "NAK",
    "M'G7^",           "MAK",     "NAK",
    "M\264^",             "MAK",     "NAK",
    "M'^",             "MAK",     "NAK",
    "M",               null,      "N",
    "NACH^^",          "NACH",    "NAK",
    "NADINE^$",        "NADIN",   "NATIN",
    "NAIV--",          "NA",      "NA",
    "NAISE$",          "NESE",    "NEZE",
    "NAUGENOMM------", "NAU ",    "NAU ",
    "NAUSOGUT$",     "NAUSO GUT", "NAUZU KUT",
    "NCH$",            "NSH",     "NZ",
    "NCOISE$",         "SOA",     "ZUA",
    "NCOIS$",          "SOA",     "ZUA",
    "NDAR$",           "NDA",     "NTA",
    "NDERINGEN------", "NDE ",    "NTE ",
    "NDRO(CDKTZ)-",    "NTRO",    null,
    "ND(BFGJLMNPQVW)-", "NT",     null,
    "ND(S\337Z)$",        "NS",      "NZ",
    "N\307OISE$",         "SOA",     "ZUA",
    "N\307OIS$",          "SOA",     "ZUA",
    "ND'S$",           "NS",      "NZ",
    "ND\264S$",           "NS",      "NZ",
    "NEBEN^^",         "NEBN",    "NEBN",
    "NENGELERN------", "NEN ",    "NEN ",
    "NENLERN(ET)---",  "NEN LE",  "NEN LE",
    "NENZULERNE---", "NEN ZU LE", "NEN ZU LE",
    "NE(LMNRST)-3^",   "NE",      "NE",
    "NEN-3",           "NE",      "NE",
    "NETTE$",          "NET",     "NET",
    "NGU^^",           "NU",      "NU",
    "NG(BDFJLMNPQRTVW)-", "NK",   "NK",
    "NH(AUO)-$",       "NI",      "NI",
    "NICHTSAHNEN-----", "NIX ",   "NIX ",
    "NICHTSSAGE----",  "NIX ",    "NIX ",
    "NICHTS^^",        "NIX",     "NIX",
    "NICHT^^",         "NICHT",   "NIKT",
    "NINE$",           "NIN",     "NIN",
    "NON^^",           "NON",     "NUN",
    "NOTLEIDE-----^",  "NOT ",    "NUT ",
    "NOT^^",           "NOT",     "NUT",
    "NTI(AIOU)-3",     "NZI",     "NZI",
    "NTIEL--3",        "NZI",     "NZI",
    "NTYNA",           "NTINA",   "NTINA",
    "NT(S\337Z)$",        "NS",      "NZ",
    "NT'S$",           "NS",      "NZ",
    "NT\264S$",           "NS",      "NZ",
    "NYLON",           "NEILON",  "NEILUN",
    "NY9^",            "NUE",      null,
    "NSTZUNEH---",     "NST ZU ", "NZT ZU ",
    "NSZ-",            "NS",      null,
    "NSTS$",           "NS",      "NZ",
    "NZ(BDFGKLMNPQRSTVWX)-", "NS", null,
    "N(S\337Z)$",         "NS",      null,
    "OBERE-",          "OBER",    null,
    "OBER^^",          "OBA",     "UBA",
    "OEU2",            "OE",       "\326",
    "OE<2",            "OE",       "\326",
    "OGL-",            "OK",      null,
    "OGNIE-",          "ONI",     "UNI",
    "OGN(AEOU)-$",     "ONI",     "UNI",
    "OH(AIO\326U\334Y)-",    "OH",      null,
    "OIE$",            "OE",       "\326",
    "OIRE$",           "OA",      "UA",
    "OIR$",            "OA",      "UA",
    "OIX",             "OA",      "UA",
    "OI<3",            "EU",      "EU",
    "OKAY^$",          "OKE",     "UKE",
    "OLE(KX)-^",       "ALE",     "ALE",
    "OLYN$",           "OLIN",    "ULIN",
    "OO(DLMZ)-",       "U",       null,
    "OO$",             "U",       null,
    "OO-",             "",        "",
    "ORGINAL-----",    "ORI",     "URI",
    "OTI(A\304O\326U\334)-",    "OZI",     "UZI",
    "OUI^",            "WI",      "FI",
    "OUILLE$",         "ULIE",    "ULIE",
    "OU(DT)-^",        "AU",      "AU",
    "OUSE$",           "AUS",     "AUZ",
    "OUT-",            "AU",      "AU",
    "OU",              "U",       "U",
    "O(FV)$",          "AU",      "AU",  /****  due to "OW$" -> "AU"  ****/
    "OVER--<",         "OW",      null,
    "OV(AOU)-",        "OW",      null,
    "OW$",             "AU",      "AU",
    "OWS$",            "OS",      "UZ",
    "OJ(A\304EIO\326U\334)--",  "O",       "U",
    "OYER",            "OIA",     null,
    "OY(A\304EIO\326U\334)--",  "O",       "U",
    "O(JY)<",          "EU",      "EU",
    "OZ$",             "OS",      null,
    "O\264^",             "O",       "U",
    "O'^",             "O",       "U",
    "O",               null,      "U",
    "PATIEN--^",       "PAZI",    "PAZI",
    "PENSIO-^",        "PANSI",   "PANZI",
    "PE(LMNRST)-3^",   "PE",      "PE",
    "PFER-^",          "FE",      "FE",
    "P(FH)<",          "F",       "F",
    "PIC^$",           "PIK",     "PIK",
    "PIC$",            "PIZ",     "PIZ",
    "PIPELINE",       "PEIBLEIN", "PEIBLEIN",
    "POLYP-",          "POLUE",    null,
    "POLY^^",          "POLI",    "PULI",
    "PORTRAIT7",       "PORTRE",  "PURTRE",
    "POWER7",          "PAUA",    "PAUA",
    "PP(FH)--<",       "B",       "B",
    "PP-",             "",        "",
    "PRODUZ-^",        "PRODU",   "BRUTU",
    "PRODUZI--",       " PRODU",  " BRUTU",
    "PRIX^$",          "PRI",     "PRI",
    "PS-^^",           "P",       null,
    "P(S\337Z)^",         null,      "Z",
    "P(S\337Z)$",         "BS",      null,
    "PT-^",            "",        "",
    "PTI(A\304O\326U\334)-3",   "BZI",     "BZI",
    "PY9^",            "PUE",      null,
    "P(A\304EIO\326RU\334Y)-",  "P",       "P",
    "P(\300\301\302\303\305\310\311\312\314\315\316\331\332\333)-", "P",    null,
    "P.^",             null,      "P.",
    "P^",              "P",       null,
    "P",               "B",       "B",
    "QI-",             "Z",       "Z",
    "QUARANT--",       "KARA",    "KARA",
    "QUE(LMNRST)-3",   "KWE",     "KFE",
    "QUE$",            "K",       "K",
    "QUI(NS)$",        "KI",      "KI",
    "QUIZ7",           "KWIS",    null,
    "Q(UV)7",          "KW",      "KF",
    "Q<",              "K",       "K",
    "RADFAHR----",     "RAT ",    "RAT ",
    "RAEFTEZEHRE-----", "REFTE ", "REFTE ",
    "RAGNHIL-^",       "RANGI",   "RANKI",
    "RCH",             "RCH",     "RK",
    "REA(DU)---3^",    "R",       null,
    "REBSERZEUG------", "REBS ",  "REBZ ",
    "RECHERCH^",       "RESHASH", "REZAZ",
    "RECYCL--",        "RIZEI",  "RIZEI",
    "RE(ALST)-3^",     "RE",      null,
    "REE$",            "RI",      "RI",
    "RER$",            "RA",      "RA",
    "RE(MNR)-4",       "RE",      "RE",
    "RETTE$",          "RET",     "RET",
    "REUZ$",           "REUZ",    null,
    "REW$",            "RU",      "RU",
    "RH<^",            "R",       "R",
    "RJA(MN)--",       "RI",      "RI",
    "ROWD-^",          "RAU",     "RAU",
    "RTEMONNAIE-",     "RTMON",   "RTNUN",
    "RTI(A\304O\326U\334)-3",   "RZI",     "RZI",
    "RTIEL--3",        "RZI",     "RZI",
    "RV(AEOU)-3",      "RW",      null,
    "RY(KN)-$",        "RI",      "RI",
    "RY9^",            "RUE",      null,
    "R\304FTEZEHRE-----", "RAEFTE ",  "REFTE ",


    "SANKT^-2",        "SNT",     "ZNT",
    "SAINT^-2",        "SNT",     "ZNT",
    "SANT^-1",         "SNT",     "ZNT",
    "SKT^",            "SNT",     "ZNT",
    "STR.",            "STRASE",    "ZTRASE",
    "ST ^",            "SNT",     "ZNT",
    "ST.^",            "SNT",     "ZNT",

    "SAISO-^",         "SES",     "ZEZ",
    "SAFE^$",          "SEIF",    "ZEIF",
    "SASA^$",          "SASHA",   null,
    "SAUCE-^",         "SOS",     "ZUZ",
    "SCHLAGGEBEN-----<", "SHLAK ", "ZLAK ",
    "SCHSCH---7",      "",        "",
    "SCHTSCH",         "SH",      "Z",
    "SC(HZ)<",         "SH",      "Z",
    "SC",              "SK",      "ZK",
    "SELBSTST--7^^",   "SELB",    "ZELB",
    "SELBST7^^",       "SELBST",  "ZELBZT",
    "SERGI(IJY)^$",    "SERGEI",  "ZERKEI",
    "SERHI(IJY)^$",    "SERGEI",  "ZERKEI",
    "SERVICE7^",       "SOERWIS",  "Z\326RFIZ",
    "SERVI-^",         "SERW",    null,
    "SE(LMNRST)-3^",   "SE",      "ZE",
    "SETTE$",          "SET",     "ZET",
    "SHP-^",           "S",       "Z",
    "SHST",            "SHT",     "ZT",
    "SHTSH",           "SH",      "Z",
    "SHT",             "ST",      "Z",
    "SHY9^",           "SHUE",     null,
    "SH^^",            "SH",      null,
    "SH3",             "SH",      "Z",
    "SIARHE-^",        "SERG",    "ZERK",
    "SICHERGEGAN-----^", "SICHA ", "ZIKA ",
    "SICHERGEHE----^", "SICHA ",  "ZIKA ",
    "SICHERGESTEL------^", "SICHA ", "ZIKA ",
    "SICHERSTELL-----^", "SICHA ", "ZIKA ",
    "SICHERZU(GS)--^", "SICHA ZU ", "ZIKA ZU ",
    "SIEGLI-^",        "SIKL",    "ZIKL",
    "SIGLI-^",         "SIKL",    "ZIKL",
    "SIGHT",           "SEIT",    "ZEIT",
    "SIGN",            "SEIN",    "ZEIN",
    "SKI(NPZ)-",       "SKI",     "ZKI",
    "SKI<^",           "SHI",     "ZI",
    "SODASS^$",        "SO DAS",  "ZU TAZ",
    "SODA\337^$",         "SO DAS",  "ZU TAZ",
    "SOGENAN--^",      "SO GEN",  "ZU KEN",
    "SOEST^$",         "SOST",    "ZUZT",
    "SOUND-",          "SAUN",    "ZAUN",
    "STAATS^^",        "STAZ",    "ZTAZ",
    "STADT^^",         "STAT",    "ZTAT",
    "STANDE$",         " STANDE", " ZTANTE",
    "START^^",         "START",   "ZTART",
    "STAURANT7",       "STORAN",  "ZTURAN",
    "STEAK-",          "STE",     "ZTE",
    "STEPHEN-^$",      "STEW",    null,
    "STERN",           "STERN",   null,
    "STRAF^^",         "STRAF",   "ZTRAF",
    "ST'S$",           "Z",       "Z",
    "ST\264S$",           "Z",       "Z",
    "STST--",          "",        "",
    "STS(ACE\310\311\312HI\314\315\316OU\304\334\326)--", "ST", "ZT",
    "ST(SZ)",          "Z",       "Z",
    "SPAREN---^",      "SPA",     "ZPA",
    "SPAREND----",     " SPA",    " ZPA",
    "S(PTW)-^^",       "S",       null,
    "SP",              "SP",      null,
    "STYN(AE)-$",      "STIN",    "ZTIN",
    "STR.",            "STRASE",    "ZTRASE",
    "ST",              "ST",      "ZT",
    "SUITE<",          "SIUT",    "ZIUT",
    "SUKE--$",         "S",       "Z",
    "SURF(EI)-",       "SOERF",    "Z\326RF",
    "SV(AE\310\311\312I\314\315\316OU)-<^", "SW",   null,
    "SYB(IY)--^",      "SIB",     null,
    "SYL(KVW)--^",     "SI",      null,
    "SY9^",            "SUE",      null,
    "SZE(NPT)-^",      "ZE",      "ZE",
    "SZI(ELN)-^",      "ZI",      "ZI",
    "SZCZ<",           "SH",      "Z",
    "SZT<",            "ST",      "ZT",
    "SZ<3",            "SH",      "Z",
    "S\334L(KVW)--^",     "SI",      null,
    
    "S.",              "SNT",     "ZNT",
    "S. ",             "SNT",     "ZNT",
    "S.-",             "SNT",     "ZNT",

    "S",               null,      "Z",
    "TATSIANA^$",      "TATIANA", "TATIANA",
    "TCH",             "SH",      "Z",
    "TD(A\304EIO\326RU\334Y)-", "T",       null,
    "TD(\300\301\302\303\305\310\311\312\313\314\315\316\317\322\323\324\325\330\331\332\333\335\237)-", "T", null,
    "TEAT-^",          "TEA",     "TEA",
    "TERRAI7^",        "TERA",    "TERA",
    "TET(IJY)--^",     "TA",      "TA",
    "TE(LMNRST)-3^",   "TE",      "TE",
    "TH<",             "T",       "T",
    "TICHT-",          "TIK",     "TIK",
    "TICH$",           "TIK",     "TIK",
    "TIC$",            "TIZ",     "TIZ",
    "TIGGESTELL-------", "TIK ",  "TIK ",
    "TIGSTELL-----",   "TIK ",    "TIK ",
    "TOAS-^",          "TO",      "TU",
    "TOILET-",         "TOLE",    "TULE",
    "TOIN-",           "TOA",     "TUA",
    "TRAECHTI-^",      "TRECHT",  "TREKT",
    "TRAECHTIG--",     " TRECHT", " TREKT",
    "TRAINI-",         "TREN",    "TREN",
    "TR\304CHTI-^",       "TRAECHT",  "TREKT",
    "TR\304CHTIG--",      " TRAECHT", " TREKT",
    "TSCH",            "SH",      "Z",
    "TSH",             "SH",      "Z",
    "TST",             "ZT",      "ZT",
    "T(S\337)",           "Z",       "Z",
    "TT(SZ)--<",       "",        "",
    "TT9",             "T",       "T",
    "TV^$",            "TV",      "TV",
    "TX(AEIOU)-3",     "SH",      "Z",
    "TY9^",            "TUE",      null,
    "TZ-",             "",        "",
    "T'S3$",           "Z",       "Z",
    "T\264S3$",           "Z",       "Z",
    "UEBEL(GNRW)-^^",  "UEBL ",    "IBL ",
    "UEBER^^",         "UEBA",     "IBA",
    "UE2",             "UE",       "I",
    "UGL-",            "UK",      null,
    "UH(AO\326U\334Y)-",     "UH",      null,
    "UIE$",            "UE",       "I",
    "ULADZIMIR^$",    "WLADIMIR", "FLATINIR",
    "UM^^",            "UM",      "UN",
    "UNTERE--3",       "UNTE",    "UNTE",
    "UNTER^^",         "UNTA",    "UNTA",
    "UNVER^^",         "UNFA",    "UNFA",
    "UN^^",            "UN",      "UN",
    "UTI(A\304O\326U\334)-",    "UZI",     "UZI",
    "UVE-4",           "UW",      null,
    "UY2",             "UI",      null,
    "UZZ",             "AS",      "AZ",
    "VACL-^",          "WAZ",     "FAZ",
    "VAC$",            "WAZ",     "FAZ",
    "VAD(IY)^",        "WADI",    null,
    "VAN DEN ^",       "FANDN",   "FANTN",
    "VANES-^",         "WANE",    null,
    "VASYL^$",         "WASIL",   null,
    "VATRO-",          "WATR",    null,
    "VA(DHJNT)--^",    "F",       null,
    "VEDD-^",          "FE",      "FE",
    "VE(BEHIU)--^",    "F",       null,
    "VEL(BDLMNT)-^",   "FEL",     null,
    "VENTZ-^",         "FEN",     null,
    "VEN(NRSZ)-^",     "FEN",     null,
    "VER(AB)-^$",      "WER",     null,
    "VERBAL^$",        "WERBAL",  null,
    "VERBAL(EINS)-^",  "WERBAL",  null,
    "VERTEBR--",       "WERTE",   null,
    "VEREIN-----",     "F",       null,
    "VEREN(AEIOU)-^",  "WEREN",   null,
    "VERIFI",          "WERIFI",  null,
    "VERON(AEIOU)-^",  "WERON",   null,
    "VERSEN^",         "FERSN",   "FAZN",
    "VERSIERT--^",     "WERSI",   null,
    "VERSIO--^",       "WERS",    null,
    "VERSUS",          "WERSUS",  null,
    "VERTI(GK)-",      "WERTI",   null,
    "VER^^",           "FER",     "FA",
    "VERSPRECHE-------", " FER",  " FA",
    "VER$",            "WA",      null,
    "VER",             "FA",      "FA",
    "VET(HT)-^",       "FET",     "FET",
    "VETTE$",          "WET",     "FET",
    "VE^",             "WE",      null,
    "VIC$",            "WIZ",     "FIZ",
    "VIELSAGE----",    "FIL ",    "FIL ",
    "VIEL",            "FIL",     "FIL",
    "VIEW",            "WIU",     "FIU",
    "VIKTAR^$",        "WIKTOR",  "FIKTUR",
    "VILL(AE)-",       "WIL",     null,
    "VIS(ACEIKUVWZ)-<^", "WIS",   null,
    "VI(ELS)--^",      "F",       null,
    "VILLON--",        "WILI",    "FILI",
    "VIZE^^",          "FIZE",    "FIZE",
    "VLADYS-^",        "WLADI",   "FLATI",
    "VLIE--^",         "FL",      null,
    "VL(AEIOU)--",     "W",       null,
    "VOIGT-",          "FOK",     "FUK",
    "VOKA-^",          "WOK",     null,
    "VOLHA^$",         "OLGA",    "ULKA",
    "VOLODIMIR^$",    "WLADIMIR", null,
    "VOLODYMYR^$",    "WLADIMIR", null,
    "VOL(ATUVW)--^",   "WO",      null,
    "VOR^^",           "FOR",     "FUR",
    "VR(AEIOU)--",     "W",       null,
    "VV9",             "W",       null,
    "VY9^",            "WUE",      "FI",
    "V(\334Y)-",          "W",       null,
    "V(\300\301\302\303\305\310\311\312\314\315\316\331\332\333)-",  "W",   null,
    "V(AEIJLRU)-<",    "W",       null,
    "V.^",             "V.",      null,
    "V<",              "F",       "F",
    "WEITERENTWI-----^", "WEITA ", "FEITA ",
    "WEITREICH-----^", "WEIT ",   "FEIT ",
    "WEITVER^",       "WEIT FER", "FEIT FA",
    "WE(LMNRST)-3^",   "WE",      "FE",
    "WER(DST)-",       "WER",     null,
    "WIC$",            "WIZ",     "FIZ",
    "WIEDERU--",       "WIDE",    "FITE",
    "WIEDER^$",        "WIDA",    "FITA",
    "WIEDER^^",        "WIDA ",   "FITA ",
    "WIEGMAN-^",       "WICHMA",  null,
    "WIEVIEL",         "WI FIL",  "FI FIL",
    "WISUEL",          "WISUEL",  null,
    "WLADI-^",         "WLAD",    null,
    "WR-^",            "W",       null,
    "WY9^",            "WUE",      "FI",
    "W(BDFGJKLMNPQRSTZ)-", "F",   null,
    "W$",              "F",       null,
    "W",               null,      "F",
    "X<^",             "Z",       "Z",
    "XHAVEN$",         "XAFN",    null,
    "X(CSZ)",          "X",       "X",
    "XTS(CH)--",       "XT",      "XT",
    "XT(SZ)",          "Z",       "Z",
    "YAUHEN-",         "IEFGE",   "IEFKE",
    "YE(LMNRST)-3^",   "IE",      "IE",
    "YE-3",            "I",       "I",
    "YOR(GK)^$",       "IOERK",    "I\326RK",
    "Y(AOU)-<7",       "I",       "I",
    "Y(BKLMNPRSTX)-1", "UE",       null,
    "YVES^$",          "IF",      "IF",
    "YVONNE^$",        "IWON",    "IFUN",
    "Y.^",             "Y.",      null,
    "Y",               "I",       "I",
    "ZC(AOU)-",        "SK",      "ZK",
    "ZE(LMNRST)-3^",   "ZE",      "ZE",
    "ZIEJ$",           "ZI",      "ZI",
    "ZIGERJA(HR)-3",   "ZIGA IA", "ZIKA IA",
    "ZL(AEIOU)-",      "SL",      null,
    "ZS(CHT)--",       "",        "",
    "ZS",              "SH",      "Z",
    "ZUERST",          "ZUERST",  "ZUERST",
    "ZUGRUNDE^$",    "ZU GRUNDE", "ZU KRUNTE",
    "ZUGRUNDE",     "ZU GRUNDE ", "ZU KRUNTE ",
    "ZUGUNSTEN",     "ZU GUNSTN", "ZU KUNZTN",
    "ZUHAUSE-",        "ZU HAUS", "ZU AUZ",
    "ZULASTEN^$",     "ZU LASTN", "ZU LAZTN",
    "ZURUECK^^",       "ZURUEK",   "ZURIK",
    "ZURZEIT",        "ZUR ZEIT", "ZUR ZEIT",
    "ZUR\334CK^^",        "ZURUEK",   "ZURIK",
    "ZUSTANDE",      "ZU STANDE", "ZU ZTANTE",
    "ZUTAGE",          "ZU TAGE", "ZU TAKE",
    "ZUVER^^",         "ZUFA",    "ZUFA",
    "ZUVIEL",          "ZU FIL",  "ZU FIL",
    "ZUWENIG",        "ZU WENIK", "ZU FENIK",
    "ZY9^",            "ZUE",      null,
    "ZYK3$",           "ZIK",     null,
    "Z(VW)7^",         "SW",      null,

    PHONET_END,      PHONET_END,  PHONET_END
  };

#endif    /****  PHONET_GERMAN  ****/




static int set_phonet_language (int rule_set)
/****  result:  0 :  success             ****/
/****          -1 :  language not found  ****/
{
 switch (rule_set)
   {
    #ifdef PHONET_NO_LANGUAGE
         case PHONET_NO_LANGUAGE :
                   phonet_language = phonet_language_no_language;
                   phonet_init   = & phonet_init_no_language;
                   phonet_hash   = phonet_hash_no_language;
                   phonet_hash_1 = & phonet_hash_no_language_1;
                   phonet_hash_2 = & phonet_hash_no_language_2;
                   phonet_rules  = phonet_rules_no_language;
             return (0);
    #endif

    #ifdef PHONET_ENGLISH
         case PHONET_ENGLISH :
                   phonet_language = phonet_language_english;
                   phonet_init   = & phonet_init_english;
                   phonet_hash   = phonet_hash_english;
                   phonet_hash_1 = & phonet_hash_english_1;
                   phonet_hash_2 = & phonet_hash_english_2;
                   phonet_rules  = phonet_rules_english;
             return (0);
    #endif

    #ifdef PHONET_GERMAN
         case PHONET_GERMAN  :
                   phonet_language = phonet_language_german;
                   phonet_init   = & phonet_init_german;
                   phonet_hash   = phonet_hash_german;
                   phonet_hash_1 = & phonet_hash_german_1;
                   phonet_hash_2 = & phonet_hash_german_2;
                   phonet_rules  = phonet_rules_german;
             return (0);
    #endif
   }
 return (-1);
}

#endif     /****  _PHONET_H_  ****/


/************************************************************/
/****  end of file "phonet.h"  ******************************/
/************************************************************/
